// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj1BFZMWzYKU_kbhLx6fyW2fWG4_FgIKU',
    appId: '1:704660331408:web:ff829491a1a3549ee4f115',
    messagingSenderId: '704660331408',
    projectId: 'shalldu-c9024',
    authDomain: 'shalldu-c9024.firebaseapp.com',
    storageBucket: 'shalldu-c9024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAURJOmokCXs8MA0epqYvAxD0OwbL1W8QM',
    appId: '1:704660331408:android:d4ebe19a97c6c77ae4f115',
    messagingSenderId: '704660331408',
    projectId: 'shalldu-c9024',
    storageBucket: 'shalldu-c9024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJKAfX2tsC_c26sk-dthClvdJLk-X7e4Q',
    appId: '1:704660331408:ios:9bcc27faa95ce40ee4f115',
    messagingSenderId: '704660331408',
    projectId: 'shalldu-c9024',
    storageBucket: 'shalldu-c9024.appspot.com',
    iosClientId: '704660331408-0k8rktsf1fse9fleersufrfkcpsi7h40.apps.googleusercontent.com',
    iosBundleId: 'com.example.sqliteProviderStarter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj1BFZMWzYKU_kbhLx6fyW2fWG4_FgIKU',
    appId: '1:704660331408:web:f8a004f6779578e8e4f115',
    messagingSenderId: '704660331408',
    projectId: 'shalldu-c9024',
    authDomain: 'shalldu-c9024.firebaseapp.com',
    storageBucket: 'shalldu-c9024.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBj1BFZMWzYKU_kbhLx6fyW2fWG4_FgIKU',
    appId: '1:704660331408:web:c7548af61e1ea70be4f115',
    messagingSenderId: '704660331408',
    projectId: 'shalldu-c9024',
    authDomain: 'shalldu-c9024.firebaseapp.com',
    storageBucket: 'shalldu-c9024.appspot.com',
  );
}
